;;Code to implement generation 0
(load "composition.lisp")
(setq complist_gen_0_fun_0 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_0 (list 'c 'b 'c ))
(compose gen_0_fun_0_unpinched div complist_gen_0_fun_0 ) 
(pinch gen_0_fun_0 gen_0_fun_0_unpinched pinchlist_gen_0_fun_0 ) 
(setq complist_gen_0_fun_1 (list None (safe-function one)))
(setq pinchlist_gen_0_fun_1 (list 'a ))
(compose gen_0_fun_1_unpinched minus complist_gen_0_fun_1 ) 
(pinch gen_0_fun_1 gen_0_fun_1_unpinched pinchlist_gen_0_fun_1 ) 
(setq complist_gen_0_fun_2 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_2 (list 'a 'b 'a ))
(compose gen_0_fun_2_unpinched mult complist_gen_0_fun_2 ) 
(pinch gen_0_fun_2 gen_0_fun_2_unpinched pinchlist_gen_0_fun_2 ) 
(setq complist_gen_0_fun_3 (list None None ))
(setq pinchlist_gen_0_fun_3 (list 'b 'b ))
(compose gen_0_fun_3_unpinched minus complist_gen_0_fun_3 ) 
(pinch gen_0_fun_3 gen_0_fun_3_unpinched pinchlist_gen_0_fun_3 ) 
(setq complist_gen_0_fun_4 (list None (safe-function mult)))
(setq pinchlist_gen_0_fun_4 (list 'b 'c 'a ))
(compose gen_0_fun_4_unpinched div complist_gen_0_fun_4 ) 
(pinch gen_0_fun_4 gen_0_fun_4_unpinched pinchlist_gen_0_fun_4 ) 
(setq complist_gen_0_fun_5 (list ))
(setq pinchlist_gen_0_fun_5 (list ))
(compose gen_0_fun_5_unpinched one complist_gen_0_fun_5 ) 
(pinch gen_0_fun_5 gen_0_fun_5_unpinched pinchlist_gen_0_fun_5 ) 
(setq complist_gen_0_fun_6 (list None (safe-function mult)))
(setq pinchlist_gen_0_fun_6 (list 'a 'b 'c ))
(compose gen_0_fun_6_unpinched div complist_gen_0_fun_6 ) 
(pinch gen_0_fun_6 gen_0_fun_6_unpinched pinchlist_gen_0_fun_6 ) 
(setq complist_gen_0_fun_7 (list ))
(setq pinchlist_gen_0_fun_7 (list ))
(compose gen_0_fun_7_unpinched one complist_gen_0_fun_7 ) 
(pinch gen_0_fun_7 gen_0_fun_7_unpinched pinchlist_gen_0_fun_7 ) 
(setq complist_gen_0_fun_8 (list (safe-function div)(safe-function minus)))
(setq pinchlist_gen_0_fun_8 (list 'c 'd 'b 'd ))
(compose gen_0_fun_8_unpinched minus complist_gen_0_fun_8 ) 
(pinch gen_0_fun_8 gen_0_fun_8_unpinched pinchlist_gen_0_fun_8 ) 
(setq complist_gen_0_fun_9 (list None None ))
(setq pinchlist_gen_0_fun_9 (list 'a 'b ))
(compose gen_0_fun_9_unpinched mult complist_gen_0_fun_9 ) 
(pinch gen_0_fun_9 gen_0_fun_9_unpinched pinchlist_gen_0_fun_9 ) 
(setq complist_gen_0_fun_10 (list (safe-function one)None ))
(setq pinchlist_gen_0_fun_10 (list 'a ))
(compose gen_0_fun_10_unpinched mult complist_gen_0_fun_10 ) 
(pinch gen_0_fun_10 gen_0_fun_10_unpinched pinchlist_gen_0_fun_10 ) 
(setq complist_gen_0_fun_11 (list ))
(setq pinchlist_gen_0_fun_11 (list ))
(compose gen_0_fun_11_unpinched one complist_gen_0_fun_11 ) 
(pinch gen_0_fun_11 gen_0_fun_11_unpinched pinchlist_gen_0_fun_11 ) 
(setq complist_gen_0_fun_12 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_12 (list 'b 'c 'c ))
(compose gen_0_fun_12_unpinched plus complist_gen_0_fun_12 ) 
(pinch gen_0_fun_12 gen_0_fun_12_unpinched pinchlist_gen_0_fun_12 ) 
(setq complist_gen_0_fun_13 (list None (safe-function one)))
(setq pinchlist_gen_0_fun_13 (list 'a ))
(compose gen_0_fun_13_unpinched div complist_gen_0_fun_13 ) 
(pinch gen_0_fun_13 gen_0_fun_13_unpinched pinchlist_gen_0_fun_13 ) 
(setq complist_gen_0_fun_14 (list (safe-function one)(safe-function mult)))
(setq pinchlist_gen_0_fun_14 (list 'b 'a ))
(compose gen_0_fun_14_unpinched plus complist_gen_0_fun_14 ) 
(pinch gen_0_fun_14 gen_0_fun_14_unpinched pinchlist_gen_0_fun_14 ) 
(setq complist_gen_0_fun_15 (list ))
(setq pinchlist_gen_0_fun_15 (list ))
(compose gen_0_fun_15_unpinched one complist_gen_0_fun_15 ) 
(pinch gen_0_fun_15 gen_0_fun_15_unpinched pinchlist_gen_0_fun_15 ) 
(setq complist_gen_0_fun_16 (list (safe-function minus)(safe-function minus)))
(setq pinchlist_gen_0_fun_16 (list 'c 'a 'a 'c ))
(compose gen_0_fun_16_unpinched minus complist_gen_0_fun_16 ) 
(pinch gen_0_fun_16 gen_0_fun_16_unpinched pinchlist_gen_0_fun_16 ) 
(setq complist_gen_0_fun_17 (list None (safe-function div)))
(setq pinchlist_gen_0_fun_17 (list 'c 'b 'a ))
(compose gen_0_fun_17_unpinched minus complist_gen_0_fun_17 ) 
(pinch gen_0_fun_17 gen_0_fun_17_unpinched pinchlist_gen_0_fun_17 ) 
(setq complist_gen_0_fun_18 (list None (safe-function minus)))
(setq pinchlist_gen_0_fun_18 (list 'c 'b 'b ))
(compose gen_0_fun_18_unpinched plus complist_gen_0_fun_18 ) 
(pinch gen_0_fun_18 gen_0_fun_18_unpinched pinchlist_gen_0_fun_18 ) 
(setq complist_gen_0_fun_19 (list ))
(setq pinchlist_gen_0_fun_19 (list ))
(compose gen_0_fun_19_unpinched one complist_gen_0_fun_19 ) 
(pinch gen_0_fun_19 gen_0_fun_19_unpinched pinchlist_gen_0_fun_19 ) 
(setq complist_gen_0_fun_20 (list None (safe-function one)))
(setq pinchlist_gen_0_fun_20 (list 'a ))
(compose gen_0_fun_20_unpinched div complist_gen_0_fun_20 ) 
(pinch gen_0_fun_20 gen_0_fun_20_unpinched pinchlist_gen_0_fun_20 ) 
(setq complist_gen_0_fun_21 (list (safe-function one)(safe-function minus)))
(setq pinchlist_gen_0_fun_21 (list 'b 'b ))
(compose gen_0_fun_21_unpinched minus complist_gen_0_fun_21 ) 
(pinch gen_0_fun_21 gen_0_fun_21_unpinched pinchlist_gen_0_fun_21 ) 
(setq complist_gen_0_fun_22 (list ))
(setq pinchlist_gen_0_fun_22 (list ))
(compose gen_0_fun_22_unpinched one complist_gen_0_fun_22 ) 
(pinch gen_0_fun_22 gen_0_fun_22_unpinched pinchlist_gen_0_fun_22 ) 
(setq complist_gen_0_fun_23 (list ))
(setq pinchlist_gen_0_fun_23 (list ))
(compose gen_0_fun_23_unpinched one complist_gen_0_fun_23 ) 
(pinch gen_0_fun_23 gen_0_fun_23_unpinched pinchlist_gen_0_fun_23 ) 
(setq complist_gen_0_fun_24 (list (safe-function minus)(safe-function mult)))
(setq pinchlist_gen_0_fun_24 (list 'c 'c 'b 'c ))
(compose gen_0_fun_24_unpinched minus complist_gen_0_fun_24 ) 
(pinch gen_0_fun_24 gen_0_fun_24_unpinched pinchlist_gen_0_fun_24 ) 
(setq complist_gen_0_fun_25 (list (safe-function div)None ))
(setq pinchlist_gen_0_fun_25 (list 'b 'a 'a ))
(compose gen_0_fun_25_unpinched minus complist_gen_0_fun_25 ) 
(pinch gen_0_fun_25 gen_0_fun_25_unpinched pinchlist_gen_0_fun_25 ) 
(setq complist_gen_0_fun_26 (list None (safe-function minus)))
(setq pinchlist_gen_0_fun_26 (list 'b 'c 'c ))
(compose gen_0_fun_26_unpinched plus complist_gen_0_fun_26 ) 
(pinch gen_0_fun_26 gen_0_fun_26_unpinched pinchlist_gen_0_fun_26 ) 
(setq complist_gen_0_fun_27 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_27 (list 'c 'b 'c ))
(compose gen_0_fun_27_unpinched plus complist_gen_0_fun_27 ) 
(pinch gen_0_fun_27 gen_0_fun_27_unpinched pinchlist_gen_0_fun_27 ) 
(setq complist_gen_0_fun_28 (list (safe-function one)(safe-function plus)))
(setq pinchlist_gen_0_fun_28 (list 'a 'a ))
(compose gen_0_fun_28_unpinched mult complist_gen_0_fun_28 ) 
(pinch gen_0_fun_28 gen_0_fun_28_unpinched pinchlist_gen_0_fun_28 ) 
(setq complist_gen_0_fun_29 (list None (safe-function div)))
(setq pinchlist_gen_0_fun_29 (list 'b 'c 'a ))
(compose gen_0_fun_29_unpinched minus complist_gen_0_fun_29 ) 
(pinch gen_0_fun_29 gen_0_fun_29_unpinched pinchlist_gen_0_fun_29 ) 
(setq complist_gen_0_fun_30 (list (safe-function mult)(safe-function mult)))
(setq pinchlist_gen_0_fun_30 (list 'b 'b 'b 'a ))
(compose gen_0_fun_30_unpinched plus complist_gen_0_fun_30 ) 
(pinch gen_0_fun_30 gen_0_fun_30_unpinched pinchlist_gen_0_fun_30 ) 
(setq complist_gen_0_fun_31 (list (safe-function div)(safe-function minus)))
(setq pinchlist_gen_0_fun_31 (list 'a 'a 'c 'b ))
(compose gen_0_fun_31_unpinched minus complist_gen_0_fun_31 ) 
(pinch gen_0_fun_31 gen_0_fun_31_unpinched pinchlist_gen_0_fun_31 ) 
(setq complist_gen_0_fun_32 (list (safe-function plus)(safe-function plus)))
(setq pinchlist_gen_0_fun_32 (list 'b 'd 'd 'b ))
(compose gen_0_fun_32_unpinched minus complist_gen_0_fun_32 ) 
(pinch gen_0_fun_32 gen_0_fun_32_unpinched pinchlist_gen_0_fun_32 ) 
(setq complist_gen_0_fun_33 (list (safe-function minus)None ))
(setq pinchlist_gen_0_fun_33 (list 'a 'c 'c ))
(compose gen_0_fun_33_unpinched minus complist_gen_0_fun_33 ) 
(pinch gen_0_fun_33 gen_0_fun_33_unpinched pinchlist_gen_0_fun_33 ) 
(setq complist_gen_0_fun_34 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_34 (list 'a 'b 'b ))
(compose gen_0_fun_34_unpinched plus complist_gen_0_fun_34 ) 
(pinch gen_0_fun_34 gen_0_fun_34_unpinched pinchlist_gen_0_fun_34 ) 
(setq complist_gen_0_fun_35 (list None None ))
(setq pinchlist_gen_0_fun_35 (list 'a 'a ))
(compose gen_0_fun_35_unpinched minus complist_gen_0_fun_35 ) 
(pinch gen_0_fun_35 gen_0_fun_35_unpinched pinchlist_gen_0_fun_35 ) 
(setq complist_gen_0_fun_36 (list None None ))
(setq pinchlist_gen_0_fun_36 (list 'a 'a ))
(compose gen_0_fun_36_unpinched mult complist_gen_0_fun_36 ) 
(pinch gen_0_fun_36 gen_0_fun_36_unpinched pinchlist_gen_0_fun_36 ) 
(setq complist_gen_0_fun_37 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_37 (list 'b 'b 'a ))
(compose gen_0_fun_37_unpinched mult complist_gen_0_fun_37 ) 
(pinch gen_0_fun_37 gen_0_fun_37_unpinched pinchlist_gen_0_fun_37 ) 
(setq complist_gen_0_fun_38 (list None (safe-function mult)))
(setq pinchlist_gen_0_fun_38 (list 'a 'a 'c ))
(compose gen_0_fun_38_unpinched mult complist_gen_0_fun_38 ) 
(pinch gen_0_fun_38 gen_0_fun_38_unpinched pinchlist_gen_0_fun_38 ) 
(setq complist_gen_0_fun_39 (list None (safe-function one)))
(setq pinchlist_gen_0_fun_39 (list 'a ))
(compose gen_0_fun_39_unpinched minus complist_gen_0_fun_39 ) 
(pinch gen_0_fun_39 gen_0_fun_39_unpinched pinchlist_gen_0_fun_39 ) 
(setq complist_gen_0_fun_40 (list (safe-function mult)(safe-function div)))
(setq pinchlist_gen_0_fun_40 (list 'c 'd 'd 'a ))
(compose gen_0_fun_40_unpinched mult complist_gen_0_fun_40 ) 
(pinch gen_0_fun_40 gen_0_fun_40_unpinched pinchlist_gen_0_fun_40 ) 
(setq complist_gen_0_fun_41 (list ))
(setq pinchlist_gen_0_fun_41 (list ))
(compose gen_0_fun_41_unpinched one complist_gen_0_fun_41 ) 
(pinch gen_0_fun_41 gen_0_fun_41_unpinched pinchlist_gen_0_fun_41 ) 
(setq complist_gen_0_fun_42 (list ))
(setq pinchlist_gen_0_fun_42 (list ))
(compose gen_0_fun_42_unpinched one complist_gen_0_fun_42 ) 
(pinch gen_0_fun_42 gen_0_fun_42_unpinched pinchlist_gen_0_fun_42 ) 
(setq complist_gen_0_fun_43 (list None (safe-function minus)))
(setq pinchlist_gen_0_fun_43 (list 'a 'b 'b ))
(compose gen_0_fun_43_unpinched plus complist_gen_0_fun_43 ) 
(pinch gen_0_fun_43 gen_0_fun_43_unpinched pinchlist_gen_0_fun_43 ) 
(setq complist_gen_0_fun_44 (list None None ))
(setq pinchlist_gen_0_fun_44 (list 'b 'b ))
(compose gen_0_fun_44_unpinched minus complist_gen_0_fun_44 ) 
(pinch gen_0_fun_44 gen_0_fun_44_unpinched pinchlist_gen_0_fun_44 ) 
(setq complist_gen_0_fun_45 (list None (safe-function minus)))
(setq pinchlist_gen_0_fun_45 (list 'c 'a 'a ))
(compose gen_0_fun_45_unpinched mult complist_gen_0_fun_45 ) 
(pinch gen_0_fun_45 gen_0_fun_45_unpinched pinchlist_gen_0_fun_45 ) 
(setq complist_gen_0_fun_46 (list (safe-function div)None ))
(setq pinchlist_gen_0_fun_46 (list 'c 'b 'b ))
(compose gen_0_fun_46_unpinched mult complist_gen_0_fun_46 ) 
(pinch gen_0_fun_46 gen_0_fun_46_unpinched pinchlist_gen_0_fun_46 ) 
(setq complist_gen_0_fun_47 (list (safe-function one)None ))
(setq pinchlist_gen_0_fun_47 (list 'a ))
(compose gen_0_fun_47_unpinched mult complist_gen_0_fun_47 ) 
(pinch gen_0_fun_47 gen_0_fun_47_unpinched pinchlist_gen_0_fun_47 ) 
(setq complist_gen_0_fun_48 (list (safe-function mult)None ))
(setq pinchlist_gen_0_fun_48 (list 'a 'c 'b ))
(compose gen_0_fun_48_unpinched div complist_gen_0_fun_48 ) 
(pinch gen_0_fun_48 gen_0_fun_48_unpinched pinchlist_gen_0_fun_48 ) 
(setq complist_gen_0_fun_49 (list None (safe-function plus)))
(setq pinchlist_gen_0_fun_49 (list 'b 'c 'c ))
(compose gen_0_fun_49_unpinched minus complist_gen_0_fun_49 ) 
(pinch gen_0_fun_49 gen_0_fun_49_unpinched pinchlist_gen_0_fun_49 ) 
(setq complist_gen_0_fun_50 (list (safe-function mult)(safe-function plus)))
(setq pinchlist_gen_0_fun_50 (list 'd 'd 'c 'd ))
(compose gen_0_fun_50_unpinched div complist_gen_0_fun_50 ) 
(pinch gen_0_fun_50 gen_0_fun_50_unpinched pinchlist_gen_0_fun_50 ) 
(setq complist_gen_0_fun_51 (list (safe-function mult)(safe-function minus)))
(setq pinchlist_gen_0_fun_51 (list 'c 'a 'a 'c ))
(compose gen_0_fun_51_unpinched minus complist_gen_0_fun_51 ) 
(pinch gen_0_fun_51 gen_0_fun_51_unpinched pinchlist_gen_0_fun_51 ) 
(setq complist_gen_0_fun_52 (list ))
(setq pinchlist_gen_0_fun_52 (list ))
(compose gen_0_fun_52_unpinched one complist_gen_0_fun_52 ) 
(pinch gen_0_fun_52 gen_0_fun_52_unpinched pinchlist_gen_0_fun_52 ) 
(setq complist_gen_0_fun_53 (list None None ))
(setq pinchlist_gen_0_fun_53 (list 'a 'a ))
(compose gen_0_fun_53_unpinched div complist_gen_0_fun_53 ) 
(pinch gen_0_fun_53 gen_0_fun_53_unpinched pinchlist_gen_0_fun_53 ) 
(setq complist_gen_0_fun_54 (list ))
(setq pinchlist_gen_0_fun_54 (list ))
(compose gen_0_fun_54_unpinched one complist_gen_0_fun_54 ) 
(pinch gen_0_fun_54 gen_0_fun_54_unpinched pinchlist_gen_0_fun_54 ) 
(setq complist_gen_0_fun_55 (list None None ))
(setq pinchlist_gen_0_fun_55 (list 'a 'a ))
(compose gen_0_fun_55_unpinched mult complist_gen_0_fun_55 ) 
(pinch gen_0_fun_55 gen_0_fun_55_unpinched pinchlist_gen_0_fun_55 ) 
(setq complist_gen_0_fun_56 (list (safe-function one)(safe-function mult)))
(setq pinchlist_gen_0_fun_56 (list 'a 'b ))
(compose gen_0_fun_56_unpinched div complist_gen_0_fun_56 ) 
(pinch gen_0_fun_56 gen_0_fun_56_unpinched pinchlist_gen_0_fun_56 ) 
(setq complist_gen_0_fun_57 (list None (safe-function one)))
(setq pinchlist_gen_0_fun_57 (list 'a ))
(compose gen_0_fun_57_unpinched mult complist_gen_0_fun_57 ) 
(pinch gen_0_fun_57 gen_0_fun_57_unpinched pinchlist_gen_0_fun_57 ) 
(setq complist_gen_0_fun_58 (list None None ))
(setq pinchlist_gen_0_fun_58 (list 'b 'a ))
(compose gen_0_fun_58_unpinched div complist_gen_0_fun_58 ) 
(pinch gen_0_fun_58 gen_0_fun_58_unpinched pinchlist_gen_0_fun_58 ) 
(setq complist_gen_0_fun_59 (list ))
(setq pinchlist_gen_0_fun_59 (list ))
(compose gen_0_fun_59_unpinched one complist_gen_0_fun_59 ) 
(pinch gen_0_fun_59 gen_0_fun_59_unpinched pinchlist_gen_0_fun_59 ) 
(setq complist_gen_0_fun_60 (list ))
(setq pinchlist_gen_0_fun_60 (list ))
(compose gen_0_fun_60_unpinched one complist_gen_0_fun_60 ) 
(pinch gen_0_fun_60 gen_0_fun_60_unpinched pinchlist_gen_0_fun_60 ) 
(setq complist_gen_0_fun_61 (list (safe-function mult)None ))
(setq pinchlist_gen_0_fun_61 (list 'c 'a 'a ))
(compose gen_0_fun_61_unpinched div complist_gen_0_fun_61 ) 
(pinch gen_0_fun_61 gen_0_fun_61_unpinched pinchlist_gen_0_fun_61 ) 
(setq complist_gen_0_fun_62 (list None (safe-function mult)))
(setq pinchlist_gen_0_fun_62 (list 'a 'c 'c ))
(compose gen_0_fun_62_unpinched mult complist_gen_0_fun_62 ) 
(pinch gen_0_fun_62 gen_0_fun_62_unpinched pinchlist_gen_0_fun_62 ) 
(setq complist_gen_0_fun_63 (list ))
(setq pinchlist_gen_0_fun_63 (list ))
(compose gen_0_fun_63_unpinched one complist_gen_0_fun_63 ) 
(pinch gen_0_fun_63 gen_0_fun_63_unpinched pinchlist_gen_0_fun_63 ) 
(setq complist_gen_0_fun_64 (list ))
(setq pinchlist_gen_0_fun_64 (list ))
(compose gen_0_fun_64_unpinched one complist_gen_0_fun_64 ) 
(pinch gen_0_fun_64 gen_0_fun_64_unpinched pinchlist_gen_0_fun_64 ) 
(setq complist_gen_0_fun_65 (list (safe-function mult)(safe-function mult)))
(setq pinchlist_gen_0_fun_65 (list 'a 'c 'b 'b ))
(compose gen_0_fun_65_unpinched mult complist_gen_0_fun_65 ) 
(pinch gen_0_fun_65 gen_0_fun_65_unpinched pinchlist_gen_0_fun_65 ) 
(setq complist_gen_0_fun_66 (list (safe-function div)(safe-function one)))
(setq pinchlist_gen_0_fun_66 (list 'a 'a ))
(compose gen_0_fun_66_unpinched div complist_gen_0_fun_66 ) 
(pinch gen_0_fun_66 gen_0_fun_66_unpinched pinchlist_gen_0_fun_66 ) 
(setq complist_gen_0_fun_67 (list ))
(setq pinchlist_gen_0_fun_67 (list ))
(compose gen_0_fun_67_unpinched one complist_gen_0_fun_67 ) 
(pinch gen_0_fun_67 gen_0_fun_67_unpinched pinchlist_gen_0_fun_67 ) 
(setq complist_gen_0_fun_68 (list (safe-function one)(safe-function div)))
(setq pinchlist_gen_0_fun_68 (list 'a 'b ))
(compose gen_0_fun_68_unpinched minus complist_gen_0_fun_68 ) 
(pinch gen_0_fun_68 gen_0_fun_68_unpinched pinchlist_gen_0_fun_68 ) 
(setq complist_gen_0_fun_69 (list (safe-function div)None ))
(setq pinchlist_gen_0_fun_69 (list 'a 'a 'c ))
(compose gen_0_fun_69_unpinched mult complist_gen_0_fun_69 ) 
(pinch gen_0_fun_69 gen_0_fun_69_unpinched pinchlist_gen_0_fun_69 ) 
(setq complist_gen_0_fun_70 (list ))
(setq pinchlist_gen_0_fun_70 (list ))
(compose gen_0_fun_70_unpinched one complist_gen_0_fun_70 ) 
(pinch gen_0_fun_70 gen_0_fun_70_unpinched pinchlist_gen_0_fun_70 ) 
(setq complist_gen_0_fun_71 (list ))
(setq pinchlist_gen_0_fun_71 (list ))
(compose gen_0_fun_71_unpinched one complist_gen_0_fun_71 ) 
(pinch gen_0_fun_71 gen_0_fun_71_unpinched pinchlist_gen_0_fun_71 ) 
(setq complist_gen_0_fun_72 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_72 (list 'b 'b 'a ))
(compose gen_0_fun_72_unpinched mult complist_gen_0_fun_72 ) 
(pinch gen_0_fun_72 gen_0_fun_72_unpinched pinchlist_gen_0_fun_72 ) 
(setq complist_gen_0_fun_73 (list (safe-function minus)None ))
(setq pinchlist_gen_0_fun_73 (list 'c 'a 'a ))
(compose gen_0_fun_73_unpinched minus complist_gen_0_fun_73 ) 
(pinch gen_0_fun_73 gen_0_fun_73_unpinched pinchlist_gen_0_fun_73 ) 
(setq complist_gen_0_fun_74 (list (safe-function minus)(safe-function plus)))
(setq pinchlist_gen_0_fun_74 (list 'b 'c 'd 'a ))
(compose gen_0_fun_74_unpinched minus complist_gen_0_fun_74 ) 
(pinch gen_0_fun_74 gen_0_fun_74_unpinched pinchlist_gen_0_fun_74 ) 
(setq complist_gen_0_fun_75 (list None (safe-function div)))
(setq pinchlist_gen_0_fun_75 (list 'b 'c 'a ))
(compose gen_0_fun_75_unpinched plus complist_gen_0_fun_75 ) 
(pinch gen_0_fun_75 gen_0_fun_75_unpinched pinchlist_gen_0_fun_75 ) 
(setq complist_gen_0_fun_76 (list ))
(setq pinchlist_gen_0_fun_76 (list ))
(compose gen_0_fun_76_unpinched one complist_gen_0_fun_76 ) 
(pinch gen_0_fun_76 gen_0_fun_76_unpinched pinchlist_gen_0_fun_76 ) 
(setq complist_gen_0_fun_77 (list (safe-function minus)None ))
(setq pinchlist_gen_0_fun_77 (list 'c 'a 'b ))
(compose gen_0_fun_77_unpinched plus complist_gen_0_fun_77 ) 
(pinch gen_0_fun_77 gen_0_fun_77_unpinched pinchlist_gen_0_fun_77 ) 
(setq complist_gen_0_fun_78 (list (safe-function minus)(safe-function plus)))
(setq pinchlist_gen_0_fun_78 (list 'c 'd 'd 'a ))
(compose gen_0_fun_78_unpinched minus complist_gen_0_fun_78 ) 
(pinch gen_0_fun_78 gen_0_fun_78_unpinched pinchlist_gen_0_fun_78 ) 
(setq complist_gen_0_fun_79 (list None (safe-function plus)))
(setq pinchlist_gen_0_fun_79 (list 'a 'b 'b ))
(compose gen_0_fun_79_unpinched div complist_gen_0_fun_79 ) 
(pinch gen_0_fun_79 gen_0_fun_79_unpinched pinchlist_gen_0_fun_79 ) 
(setq complist_gen_0_fun_80 (list None None ))
(setq pinchlist_gen_0_fun_80 (list 'a 'a ))
(compose gen_0_fun_80_unpinched div complist_gen_0_fun_80 ) 
(pinch gen_0_fun_80 gen_0_fun_80_unpinched pinchlist_gen_0_fun_80 ) 
(setq complist_gen_0_fun_81 (list (safe-function div)None ))
(setq pinchlist_gen_0_fun_81 (list 'b 'c 'a ))
(compose gen_0_fun_81_unpinched mult complist_gen_0_fun_81 ) 
(pinch gen_0_fun_81 gen_0_fun_81_unpinched pinchlist_gen_0_fun_81 ) 
(setq complist_gen_0_fun_82 (list (safe-function plus)(safe-function plus)))
(setq pinchlist_gen_0_fun_82 (list 'c 'a 'c 'b ))
(compose gen_0_fun_82_unpinched mult complist_gen_0_fun_82 ) 
(pinch gen_0_fun_82 gen_0_fun_82_unpinched pinchlist_gen_0_fun_82 ) 
(setq complist_gen_0_fun_83 (list None (safe-function div)))
(setq pinchlist_gen_0_fun_83 (list 'a 'c 'b ))
(compose gen_0_fun_83_unpinched minus complist_gen_0_fun_83 ) 
(pinch gen_0_fun_83 gen_0_fun_83_unpinched pinchlist_gen_0_fun_83 ) 
(setq complist_gen_0_fun_84 (list ))
(setq pinchlist_gen_0_fun_84 (list ))
(compose gen_0_fun_84_unpinched one complist_gen_0_fun_84 ) 
(pinch gen_0_fun_84 gen_0_fun_84_unpinched pinchlist_gen_0_fun_84 ) 
(setq complist_gen_0_fun_85 (list None None ))
(setq pinchlist_gen_0_fun_85 (list 'b 'a ))
(compose gen_0_fun_85_unpinched div complist_gen_0_fun_85 ) 
(pinch gen_0_fun_85 gen_0_fun_85_unpinched pinchlist_gen_0_fun_85 ) 
(setq complist_gen_0_fun_86 (list None None ))
(setq pinchlist_gen_0_fun_86 (list 'b 'a ))
(compose gen_0_fun_86_unpinched plus complist_gen_0_fun_86 ) 
(pinch gen_0_fun_86 gen_0_fun_86_unpinched pinchlist_gen_0_fun_86 ) 
(setq complist_gen_0_fun_87 (list None (safe-function plus)))
(setq pinchlist_gen_0_fun_87 (list 'b 'c 'c ))
(compose gen_0_fun_87_unpinched minus complist_gen_0_fun_87 ) 
(pinch gen_0_fun_87 gen_0_fun_87_unpinched pinchlist_gen_0_fun_87 ) 
(setq complist_gen_0_fun_88 (list (safe-function mult)None ))
(setq pinchlist_gen_0_fun_88 (list 'a 'c 'b ))
(compose gen_0_fun_88_unpinched minus complist_gen_0_fun_88 ) 
(pinch gen_0_fun_88 gen_0_fun_88_unpinched pinchlist_gen_0_fun_88 ) 
(setq complist_gen_0_fun_89 (list ))
(setq pinchlist_gen_0_fun_89 (list ))
(compose gen_0_fun_89_unpinched one complist_gen_0_fun_89 ) 
(pinch gen_0_fun_89 gen_0_fun_89_unpinched pinchlist_gen_0_fun_89 ) 
(setq complist_gen_0_fun_90 (list (safe-function one)(safe-function plus)))
(setq pinchlist_gen_0_fun_90 (list 'a 'a ))
(compose gen_0_fun_90_unpinched plus complist_gen_0_fun_90 ) 
(pinch gen_0_fun_90 gen_0_fun_90_unpinched pinchlist_gen_0_fun_90 ) 
(setq complist_gen_0_fun_91 (list (safe-function one)(safe-function minus)))
(setq pinchlist_gen_0_fun_91 (list 'a 'b ))
(compose gen_0_fun_91_unpinched minus complist_gen_0_fun_91 ) 
(pinch gen_0_fun_91 gen_0_fun_91_unpinched pinchlist_gen_0_fun_91 ) 
(setq complist_gen_0_fun_92 (list (safe-function plus)None ))
(setq pinchlist_gen_0_fun_92 (list 'b 'a 'a ))
(compose gen_0_fun_92_unpinched plus complist_gen_0_fun_92 ) 
(pinch gen_0_fun_92 gen_0_fun_92_unpinched pinchlist_gen_0_fun_92 ) 
(setq complist_gen_0_fun_93 (list ))
(setq pinchlist_gen_0_fun_93 (list ))
(compose gen_0_fun_93_unpinched one complist_gen_0_fun_93 ) 
(pinch gen_0_fun_93 gen_0_fun_93_unpinched pinchlist_gen_0_fun_93 ) 
(setq complist_gen_0_fun_94 (list None (safe-function plus)))
(setq pinchlist_gen_0_fun_94 (list 'c 'c 'b ))
(compose gen_0_fun_94_unpinched div complist_gen_0_fun_94 ) 
(pinch gen_0_fun_94 gen_0_fun_94_unpinched pinchlist_gen_0_fun_94 ) 
(setq complist_gen_0_fun_95 (list ))
(setq pinchlist_gen_0_fun_95 (list ))
(compose gen_0_fun_95_unpinched one complist_gen_0_fun_95 ) 
(pinch gen_0_fun_95 gen_0_fun_95_unpinched pinchlist_gen_0_fun_95 ) 
(setq complist_gen_0_fun_96 (list (safe-function div)None ))
(setq pinchlist_gen_0_fun_96 (list 'c 'a 'b ))
(compose gen_0_fun_96_unpinched plus complist_gen_0_fun_96 ) 
(pinch gen_0_fun_96 gen_0_fun_96_unpinched pinchlist_gen_0_fun_96 ) 
(setq complist_gen_0_fun_97 (list ))
(setq pinchlist_gen_0_fun_97 (list ))
(compose gen_0_fun_97_unpinched one complist_gen_0_fun_97 ) 
(pinch gen_0_fun_97 gen_0_fun_97_unpinched pinchlist_gen_0_fun_97 ) 
(setq complist_gen_0_fun_98 (list (safe-function one)None ))
(setq pinchlist_gen_0_fun_98 (list 'a ))
(compose gen_0_fun_98_unpinched div complist_gen_0_fun_98 ) 
(pinch gen_0_fun_98 gen_0_fun_98_unpinched pinchlist_gen_0_fun_98 ) 
(setq complist_gen_0_fun_99 (list (safe-function plus)(safe-function mult)))
(setq pinchlist_gen_0_fun_99 (list 'a 'a 'a 'a ))
(compose gen_0_fun_99_unpinched minus complist_gen_0_fun_99 ) 
(pinch gen_0_fun_99 gen_0_fun_99_unpinched pinchlist_gen_0_fun_99 ) 
